---

- name: Ensure rootless user group exists
  ansible.builtin.group:
    name: samba
    gid: "{{ my_linux_users.samba.gid }}"
    state: present

- name: Ensure rootless user exists
  ansible.builtin.user:
    name: samba
    state: present
    uid: "{{ my_linux_users.samba.uid }}"
    group: samba
    create_home: true

- name: Enable linger for rootless user
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger samba"
  changed_when: false

- name: Enable podman auto-update timer for rootless user # noqa: no-changed-when yaml[line-length]
  become: true
  ansible.builtin.command:
    cmd: "sudo -u samba XDG_RUNTIME_DIR=/run/user/{{ my_linux_users.samba.uid }} DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/{{ my_linux_users.samba.uid }}/bus systemctl --user enable --now podman-auto-update.timer"
  changed_when: false

- name: Save current role path
  ansible.builtin.set_fact:
    samba_role_path: "{{ role_path }}"

- name: Deploy samba container using podman_quadlet
  ansible.builtin.include_role:
    name: luckynrslevin.podman_quadlet
  vars:
    podman_quadlet_app_name: "samba"
    podman_quadlet_rootless_user_name: samba
    podman_quadlet_files_templates_src_path: "{{ samba_role_path }}"
    podman_quadlet_file_names:
      - samba.container.j2
      - samba-data.volume
    podman_quadlet_firewall_port_forwards:
      - port: 445
        proto: tcp
        toport: "{{ samba_smb_port }}"
      - port: 139
        proto: tcp
        toport: "{{ samba_netbios_port }}"
