samba_smb_port: 1445
samba_netbios_port: 1139
samba_share_path: /home/samba/share

# Samba server settings
samba_timezone: "Europe/Berlin"
samba_workgroup: "WORKGROUP"
samba_server_string: "Samba Server"
samba_netbios_name: "HOMESERVER"
