#!/usr/bin/env python3
"""
scripts/inventory_merge.py — additively merge into an inventory main.yml.

Used by `setup.sh add <service>` and `setup.sh remove <service>` to mutate
host_vars/<host>/main.yml without disturbing operator-added unmanaged
keys, comments, or formatting.

Round-trip safety: built on ruamel.yaml's typ='rt' mode, which preserves
comments, blank-line groupings, key order, and YAML tags (including
inline `!vault | ...` blocks). Re-runs that don't change anything
produce zero git diff.

Usage:
    inventory_merge.py --inventory <main.yml>
                       --vault-password-file <vault.pw>
                       --update <update.json>
                       --mode add|remove

The update.json structure (both modes use the same shape; semantics
differ by --mode):

    {
      "scalars": {
        "nextcloud_admin_password": {
          "value": "<plaintext>",
          "vault": true,
          "comment": "Auto-generated by setup.sh add nextcloud"
        },
        "nextcloud_db_password": {"value": "...", "vault": true}
      },
      "lists": {
        "deploy_services": {"items": ["nextcloud"]},
        "caddy_reverse_proxy_services": {
            "items": [{"subdomain": "cloud", "port": 8090}]
        }
      },
      "dicts": {
        "my_linux_users": {
            "entries": {"nextcloud": {"uid": 1015, "gid": 1015}}
        }
      }
    }

In add mode:
  - scalars: set <key>=<value> only if <key> doesn't already exist
    (don't clobber operator edits). Vault-encrypts when vault=true.
  - lists: append each item if not already present.
  - dicts: add each entry, leaving siblings untouched.

In remove mode:
  - scalars: delete each key from inventory (regardless of value).
  - lists: remove each item from the list (no-op if absent).
  - dicts: remove each entry key from the dict.
"""

import argparse
import json
import os
import subprocess
import sys

try:
    from ruamel.yaml import YAML
    from ruamel.yaml.comments import CommentedMap, CommentedSeq
    from ruamel.yaml.scalarstring import LiteralScalarString  # noqa: F401
except ImportError:
    print("ERROR: ruamel.yaml not installed.", file=sys.stderr)
    print("       Install: pipx inject ansible-core ruamel.yaml", file=sys.stderr)
    sys.exit(1)


def _to_commented(value):
    """Recursively convert plain dict/list to CommentedMap/CommentedSeq
    so ruamel can attach ca metadata to nested structures (needed for
    moving deep trailing comments across an insertion)."""
    if isinstance(value, dict):
        m = CommentedMap()
        for k, v in value.items():
            m[k] = _to_commented(v)
        return m
    if isinstance(value, list):
        s = CommentedSeq()
        for v in value:
            s.append(_to_commented(v))
        return s
    return value


def make_yaml() -> YAML:
    """ruamel.yaml round-trip YAML loader/dumper with sane defaults."""
    yaml = YAML(typ="rt")
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.preserve_quotes = True
    yaml.width = 4096  # don't wrap long lines (vault blocks etc.)
    return yaml


def vault_encrypt(value: str, name: str, vault_pw_file: str) -> "object":
    """Vault-encrypt <value> as <name>. Return the parsed TaggedScalar
    so it can be assigned into a ruamel.yaml document and round-tripped
    with its `!vault` tag intact.
    """
    result = subprocess.run(
        [
            "ansible-vault", "encrypt_string",
            "--encrypt-vault-id", "default",
            "--stdin-name", name,
        ],
        input=value,
        capture_output=True, text=True, check=True,
        env={**os.environ, "ANSIBLE_VAULT_PASSWORD_FILE": vault_pw_file},
    )
    # ansible-vault encrypt_string emits:
    #   <name>: !vault |
    #             $ANSIBLE_VAULT;1.1;AES256
    #             ...
    # Parse it back; the TaggedScalar is what we assign into the doc.
    yaml = make_yaml()
    fragment = yaml.load(result.stdout)
    return fragment[name]


def _append_seq_preserving_comments(seq, item):
    """Append <item> to a ruamel.yaml CommentedSeq, moving any
    after-comment from the previous-last item to the new-last item.

    ruamel attaches trailing-section comments (like `### Next section ###`)
    to the LAST item in the sequence as a "comment after". A plain
    .append() puts the new item AFTER that comment, visually leaking
    the new item into the next section. Move the comment instead.
    """
    if len(seq) == 0:
        seq.append(item)
        return
    last_idx = len(seq) - 1
    saved = seq.ca.items.pop(last_idx, None)
    seq.append(item)
    if saved is not None:
        seq.ca.items[len(seq) - 1] = saved


def _is_commented_collection(node):
    """True if <node> is a ruamel CommentedMap or CommentedSeq with items.
    TaggedScalar (e.g. !vault-wrapped strings) has .ca but is NOT a collection;
    len() on it raises TypeError."""
    if not isinstance(node, (CommentedMap, CommentedSeq)):
        return False
    try:
        return len(node) > 0
    except TypeError:
        return False

def _deepest_last_path(node):
    """Walk into the LAST entry of a CommentedMap/CommentedSeq recursively
    until we reach a scalar (or an empty/non-CommentedSeq value). Return
    a list of (parent_node, key_or_index) pairs describing the path.

    Why: ruamel attaches trailing-section comments (`### Next Section`)
    to the DEEPEST last-scalar in the previous block. To preserve them
    across an append/insert, we have to walk to that scalar, pop the
    comment, and reattach it to the deepest last-scalar of the new
    block. Without this, adding e.g. nextcloud:{uid,gid} to
    my_linux_users leaves the `### Next Section` comment stuck after
    pihole.gid, visually appearing BEFORE the new nextcloud entry.
    """
    path = []
    while True:
        if isinstance(node, CommentedMap) and len(node) > 0:
            last_key = list(node.keys())[-1]
            path.append((node, last_key))
            node = node[last_key]
        elif isinstance(node, CommentedSeq) and len(node) > 0:
            last_idx = len(node) - 1
            path.append((node, last_idx))
            node = node[last_idx]
        else:
            break
    return path


def _pop_deepest_trailing_comment(node):
    """Walk to the deepest last-item and pop its after-comment.
    Returns the saved comment (or None) and the path used."""
    path = _deepest_last_path(node)
    if not path:
        return None, []
    parent, key = path[-1]
    saved = parent.ca.items.pop(key, None) if hasattr(parent, "ca") else None
    return saved, path


def _attach_to_deepest_last(node, saved):
    """Walk to the deepest last-item of <node> and attach <saved>
    as its after-comment."""
    if saved is None:
        return
    path = _deepest_last_path(node)
    if not path:
        return
    parent, key = path[-1]
    if hasattr(parent, "ca"):
        parent.ca.items[key] = saved


def _set_dict_entry_preserving_comments(mapping, key, value):
    """Insert <key>=<value> into a ruamel.yaml CommentedMap, moving any
    after-comment from the previous-last entry to the new entry.

    Handles two cases:
    - The trailing comment is on the PREVIOUS-LAST key directly
      (flat scalar value).
    - The trailing comment is on the DEEPEST LAST-scalar of the
      previous-last entry (nested dict value, e.g. my_linux_users
      where the section comment hangs off pihole.gid).

    If <key> already exists, leaves it alone (caller decided whether
    to overwrite by checking presence first).
    """
    if key in mapping:
        return  # caller is responsible for overwrite semantics
    saved = None
    if len(mapping) > 0:
        last_key = list(mapping.keys())[-1]
        last_value = mapping[last_key]
        # Comment on the last key directly?
        saved = mapping.ca.items.pop(last_key, None)
        # If not, walk INTO the last value to find a deeper trailing comment.
        if saved is None and hasattr(last_value, "ca"):
            saved, _ = _pop_deepest_trailing_comment(last_value)
    mapping[key] = value
    if saved is not None:
        # Attach to the new entry. If the new value is a nested
        # collection, walk into it to attach at the deepest last item;
        # otherwise attach directly to the new key.
        new_value = mapping[key]
        if _is_commented_collection(new_value):
            _attach_to_deepest_last(new_value, saved)
        else:
            mapping.ca.items[key] = saved


def cmd_add(data, update, vault_pw_file):
    # scalars (top-level)
    for key, spec in (update.get("scalars") or {}).items():
        if key in data:
            continue  # don't clobber existing
        value = spec["value"]
        if spec.get("vault"):
            value = vault_encrypt(value, key, vault_pw_file)
        _set_dict_entry_preserving_comments(data, key, value)
    # lists — append-if-absent (convert items to Commented* for nested ca tracking)
    for key, spec in (update.get("lists") or {}).items():
        existing = data.get(key)
        if existing is None:
            existing = CommentedSeq()
            _set_dict_entry_preserving_comments(data, key, existing)
        for item in spec.get("items", []):
            item = _to_commented(item)
            if item not in existing:
                _append_seq_preserving_comments(existing, item)
    # dicts — merge entries
    for key, spec in (update.get("dicts") or {}).items():
        existing = data.get(key)
        if existing is None:
            existing = CommentedMap()
            _set_dict_entry_preserving_comments(data, key, existing)
        for k, v in spec.get("entries", {}).items():
            v = _to_commented(v)
            _set_dict_entry_preserving_comments(existing, k, v)


def _remove_dict_entry_preserving_comments(mapping, key):
    """Remove <key> from a CommentedMap. If it was the last entry and
    carried a trailing comment (either directly or via its deepest
    last-scalar), move the comment to the new-last entry's deepest
    last-scalar so section markers don't get orphaned/lost."""
    if key not in mapping:
        return
    is_last = list(mapping.keys())[-1] == key if len(mapping) > 0 else False
    saved = None
    if is_last:
        # Pop trailing comment from the entry being removed.
        saved = mapping.ca.items.pop(key, None)
        if saved is None and hasattr(mapping[key], "ca"):
            saved, _ = _pop_deepest_trailing_comment(mapping[key])
    del mapping[key]
    # Reattach to new-last (if any).
    if saved is not None and len(mapping) > 0:
        new_last_key = list(mapping.keys())[-1]
        new_last_value = mapping[new_last_key]
        if _is_commented_collection(new_last_value):
            _attach_to_deepest_last(new_last_value, saved)
        else:
            mapping.ca.items[new_last_key] = saved


def _remove_seq_item_preserving_comments(seq, item):
    """Remove <item> from CommentedSeq. If it was the last item and
    carried a trailing comment, move that comment to the new-last
    item's deepest last-scalar (inverse of _append_seq_preserving_comments)."""
    try:
        idx = seq.index(item)
    except ValueError:
        return
    saved = None
    is_last = idx == len(seq) - 1
    if is_last:
        saved = seq.ca.items.pop(idx, None)
        if saved is None and hasattr(seq[idx], "ca"):
            saved, _ = _pop_deepest_trailing_comment(seq[idx])
    seq.pop(idx)
    if saved is not None and len(seq) > 0:
        new_last_idx = len(seq) - 1
        new_last = seq[new_last_idx]
        if _is_commented_collection(new_last):
            _attach_to_deepest_last(new_last, saved)
        else:
            seq.ca.items[new_last_idx] = saved


def cmd_remove(data, update):
    # scalars — delete keys
    for key in (update.get("scalars") or {}).keys():
        _remove_dict_entry_preserving_comments(data, key)
    # lists — remove items
    for key, spec in (update.get("lists") or {}).items():
        existing = data.get(key)
        if existing is None:
            continue
        for item in spec.get("items", []):
            _remove_seq_item_preserving_comments(existing, item)
    # dicts — remove entry keys
    for key, spec in (update.get("dicts") or {}).items():
        existing = data.get(key)
        if existing is None:
            continue
        for k in spec.get("entries", {}).keys():
            _remove_dict_entry_preserving_comments(existing, k)


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--inventory", required=True, help="path to main.yml")
    p.add_argument("--vault-password-file", required=True, help="path to vault.pw")
    p.add_argument("--update", required=True, help="path to update.json")
    p.add_argument("--mode", choices=["add", "remove"], required=True)
    args = p.parse_args()

    yaml = make_yaml()

    if not os.path.exists(args.inventory):
        data = CommentedMap()
    else:
        with open(args.inventory) as f:
            data = yaml.load(f)
        if data is None:
            data = CommentedMap()
        elif not isinstance(data, CommentedMap):
            # Plain dict from an empty-ish doc — wrap so .ca works.
            data = CommentedMap(data)

    with open(args.update) as f:
        update = json.load(f)

    if args.mode == "add":
        cmd_add(data, update, args.vault_password_file)
    else:
        cmd_remove(data, update)

    # Write atomically to dodge half-written files on crash.
    tmp = args.inventory + ".tmp"
    with open(tmp, "w") as f:
        yaml.dump(data, f)
    os.replace(tmp, args.inventory)


if __name__ == "__main__":
    main()
